options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app-name:latest', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/your-app-name:latest']
  - name: gcr.io/cloud-builders/gcloud
    args:
      - 'run'
      - 'deploy'
      - 'your-app-name'
      - '--image=gcr.io/$PROJECT_ID/your-app-name:latest'
      - '--port=8080'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      # Optional: Add service account if needed
      # - '--service-account=your-service-account@your-project.iam.gserviceaccount.com'